# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runpod.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'runpod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crunpod.proto\x12\x06runpod\"\xed\x01\n\rRunpodRequest\x12\x11\n\x04text\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nimage_data\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x19\n\x0cimage_format\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x39\n\nparameters\x18\x04 \x03(\x0b\x32%.runpod.RunpodRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x07\n\x05_textB\r\n\x0b_image_dataB\x0f\n\r_image_format\"\xb6\x01\n\x0eRunpodResponse\x12\x18\n\x0btext_result\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nimage_data\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x19\n\x0cimage_format\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\tB\x0e\n\x0c_text_resultB\r\n\x0b_image_dataB\x0f\n\r_image_format2K\n\rRunpodService\x12:\n\x07Process\x12\x15.runpod.RunpodRequest\x1a\x16.runpod.RunpodResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runpod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNPODREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_RUNPODREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_RUNPODREQUEST']._serialized_start=25
  _globals['_RUNPODREQUEST']._serialized_end=262
  _globals['_RUNPODREQUEST_PARAMETERSENTRY']._serialized_start=172
  _globals['_RUNPODREQUEST_PARAMETERSENTRY']._serialized_end=221
  _globals['_RUNPODRESPONSE']._serialized_start=265
  _globals['_RUNPODRESPONSE']._serialized_end=447
  _globals['_RUNPODSERVICE']._serialized_start=449
  _globals['_RUNPODSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
